### PR TITLE
Update `curve25519-dalek` to 4.0.0-pre.5

### PR DESCRIPTION
**Pull request by daxpedda**
Based on https://github.com/novifinancial/voprf/pull/86 and basically the same.
Again, CI might need to be expanded, happy to add any suggestions to both PRs.

~~CI will fail until https://github.com/novifinancial/opaque-ke/pull/298.~~

### CODE REVIEW

**Comment by daxpedda** [comment]
Rebased after #298 and https://github.com/novifinancial/voprf/pull/86.
This is ready to merge, but it's a git dependency until `voprf` has a new release.

**Comment by daxpedda** [comment]
Rebased after #302.

**Comment by daxpedda** [comment]
Removed dependency patch and moved to the new `voprf` release: https://github.com/novifinancial/voprf/pull/88.

**Review by kevinlewi — APPROVED** [review]
Thanks!!

**Pull request merged**
