### PR TITLE
Backport `zeroize` fix

### PR DESCRIPTION
**Pull request by daxpedda**
As discussed in #264.

### CODE REVIEW

**Comment by daxpedda** [comment]
CI currently breaks of criterion, there is no way to really fix this. Considering it only applies to the MSRV, I consider this fine, MSRV still builds, criterion is a `dev-dependency`.

**Comment by kevinlewi** [comment]
Hmm, not a huge fan of the failing CI. Perhaps we should just update the MSRV and release a 0.7.0?

**Comment by daxpedda** [comment]
I don't think this is necessary, I can fix the CI by simply removing the benchmark and therefore the reliance on criterion.

Alternatively I can make another crate (making this a workspace) and put non-MSRV tests there, but I don't consider this worth the effort.

**Comment by kevinlewi** [comment]
Ah I see! Yes, please go ahead and remove the benchmark (for the sake of fixing CI), plus the criterion dependency. Will be happy to merge and push a new release afterwards!

**Review by kevinlewi — APPROVED** [review]

**Comment by daxpedda** [comment]
After removing criterion I encountered another issue with MSRV: `rustyline`. I didn't want to remove the examples, so continuing to follow down that path, `nix` is using `bitflags` v1, which breaks MSRV. So the latest version of `rustyline` using a version of `nix` that uses an earlier version of `bitflags` then v1, was `rustyline` v1, so I had to downgrade to that.

Turns out `proptest` is also using bitflags` v1, the earliest version of `proptest` not using `bitflags` v1 is v0.3, but that breaks everything ... looking into it.

**Comment by daxpedda** [comment]
A lot of downgrading, @kevinlewi should be good to go now.

**Review by kevinlewi — APPROVED** [review]
Thanks!

**Pull request merged**
