### PR TITLE
Update rand to 0.8 and rand_core to 0.6

### LINKED ISSUE #101: Update rand_core to 0.6
From @PaulGrandperrin in #100:

> Also as a small aside, it would be nice if you could wait for rand_core to be released in version 0.6 (rust-random/rand#1072) before releasing your 0.3 version. The new version makes it possible to use rand_core::OsRng on wasm.

We however need to also wait for curve25519-dalek + other dependencies to upgrade their `rand_core` dependency.

cc: @huitseeker

### PR DESCRIPTION
**Pull request by PaulGrandperrin**
This makes a better user experience when targeting wasm.
Closes #101

### CODE REVIEW

**Comment by PaulGrandperrin** [comment]
blocked on:

- [ ] https://github.com/dalek-cryptography/x25519-dalek/pull/64
- [ ] https://github.com/dalek-cryptography/curve25519-dalek/pull/338
- [ ] https://github.com/AltSysrq/proptest/pull/220

**Comment by PaulGrandperrin** [comment]
a small update:
- thanks to #127 , `x25519-dalek` is no longer a dependency
- `curve25519-dalek` seems to have issues with leadership and release process: the co-author of the library @hdevalence (who allegedly has been silently removed from the `dalek-cryptography` org by the other co-author) has forked it, merged the `rand` updates, and released a new major version. I changed this PR to use his version, you might want to seriously consider this change. more info here: https://github.com/dalek-cryptography/curve25519-dalek/pull/338#issuecomment-772059572
- `proptest` seems to be abandonware since September (last commit) and more worryingly, the author and Github owner (@AltSysrq) has ceased all activity since August... It looks like no change will ever be merge before the repo is forked...

**Comment by PaulGrandperrin** [comment]
I feel that this PR is ready for review but I am myself unsure about the move from `curve25519-dalek` to `curve25519-dalek-ng`.

We might get more information about the situation in response to this comment: https://github.com/dalek-cryptography/curve25519-dalek/pull/338#issuecomment-773227657

**Comment by kevinlewi** [comment]
@huitseeker : Can you also take a look here and provide your thoughts on the move to `curve25519-dalek-ng`? I don't think there are any blockers left for this PR other than this one point.

**Comment by PaulGrandperrin** [comment]
FYI: https://github.com/dalek-cryptography/curve25519-dalek/issues/345

**Comment by kevinlewi** [comment]
@PaulGrandperrin, can you take a look at #131 and see if that should suffice, instead of merging this one?

**Pull request closed without merging**
