### PR TITLE
Upgrade zeroize to 1.5

### PR DESCRIPTION
**Pull request by nitnelave**
This would allow compatibility between this older version and the newer ecosystem.

Alternatively, we could just specify "^1.1" to make sure it's _at least_ 1.1.

### CODE REVIEW

**Comment by nitnelave** [comment]
I had to push a change with lots of tiny clippy fixes to satisfy the CI, I can split it into a separate PR if you want.

**Comment by kevinlewi** [comment]
The changes look good to me, but out of curiosity, are you hoping to have a new release to the 0.6 branch (0.6.2 for instance)? Or does it suffice for your needs to simply rebase off of the revision containing these patches?

I was not planning on continuing to support the 0.6 branch since it is superseded by v2.0.

**Review by kevinlewi — APPROVED** [review]

**Comment by nitnelave** [comment]
If possible, I'd like to have a 0.6.2 release with this patch, but otherwise I can depend on the specific branch.

I know that v2.0 is better, but as we talked about it's data incompatible, so upgrading would require everyone to reset their passwords. I'd like to avoid that if possible.

**Comment by kevinlewi** [comment]
Because this change is not entirely backwards-compatible (increase in MSRV and zeroize version), I don't think we should include it in a 0.6.2. At the very least, it should be a new version (like 0.7), but this might cause confusion with the newer v2.0. Let's keep it without attaching to a specific release for now.

**Pull request merged**
